# version: "3.9"
# services:
# db:
#   image: postgres
#   environment:
#     POSTGRESS_PASSWORD: password
#     POSTGRES_USER: postgres
#     POSTGRES_DB: todo_database
#   volumes:
#     - ./pgdata:var/lob/postgresql/data
#   ports:
#     - "5432:5432"
# web:
#   image: api-with-postgres
#   depends_on: 
#     - db
#   ports: 
#     - "3050:3050"  

version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5433/todo_database
      NODE_ENV: development
      PORT: 3050
    ports:
      - "3050:3050"
    # command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_database

